### ISSUE TITLE
SMTPException: SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by rndmh3ro** [posativ/isso#185]
Python 2.6.6
Isso version: 0.9.9
When starting isso or when isso tries to send a mail the following exception occurs:
```
/usr/local/lib/python2.6/dist-packages/isso/core.py:139: DeprecationWarning: You passed a bytestring as `filenames`. This will not work on Python 3. Use `cp.read_file()` or switch to using Unicode strings across the board.
  rv.read(configfile)
2015-04-08 20:33:21,302 ERROR: unable to connect to SMTP server
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/isso/ext/notifications.py", line 42, in __init__
    with self:
  File "/usr/local/lib/python2.6/dist-packages/isso/ext/notifications.py", line 75, in __enter__
    self.client.login(username, password)
  File "/usr/lib/python2.6/smtplib.py", line 552, in login
    raise SMTPException("SMTP AUTH extension not supported by server.")
SMTPException: SMTP AUTH extension not supported by server.
```
My configuration:
```
[general]
notify = smtp
[smtp]
host = localhost
port = 25
security = none
```

With isso version 0.9.8 the problem does not happen.

**Comment by posativ** [comment]
Should be fixed with 0.9.10.
