### ISSUE TITLE
When posting a new comment:     AttributeError: 'module' object has no attribute 'spool'

### ISSUE THREAD

**Issue by xuhdev** [posativ/isso#187]
When I post a new comment I got the following error:

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/isso/__init__.py", line 136, in dispatch
        response = handler(request.environ, request, **values)
      File "/usr/local/lib/python2.7/dist-packages/isso/views/comments.py", line 84, in dec
        return func(self, env, req, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/isso/views/__init__.py", line 45, in dec
        return func(cls, env, req, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/isso/views/comments.py", line 215, in new
        self.signal("comments.new:after-save", thread, rv)
      File "/usr/local/lib/python2.7/dist-packages/isso/ext/__init__.py", line 17, in __call__
        subscriber(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/isso/ext/notifications.py", line 122, in notify
        uwsgi.spool({b"subject": thread["title"].encode("utf-8"),
    AttributeError: 'module' object has no attribute 'spool'

**Comment by posativ** [comment]
Build uWSGI with the spool module.

**Comment by xuhdev** [comment]
It turned out that this issue is caused by a non-existent spooler directory I specified. Maybe this can be added to the troubleshooting page?

**Comment by mhassan1991** [comment]
I am getting same error. I have made configuration for spooler. My .ini file is as follow.

[uwsgi]
socket = /tmp/uwsgi_worksteps.socket
processes = 4
threads = 2
wsgi-file = apache/django.wsgi
uid = deploy
gid = www-data
python-path =
touch-chain-reload = /srv/www/worksteps/current
chdir = /srv/www/worksteps/current
virtualenv = /srv/www/worksteps/shared/env
master = true
max-requests = 1
chmod = 770
hook-post-fork = chdir:/srv/www/worksteps/current
spooler = /srv/www/worksteps/current/spooler
spooler-import = /srv/www/worksteps/current/testing/tasks
spooler-processes = 5

Is there any thing wrong?

**Comment by xuhdev** [comment]
@mhassan1991 You need to create the spooler directory

**Comment by mhassan1991** [comment]
Thanx. It is working now.
