### ISSUE TITLE
[support] Isso does not work!?

### ISSUE THREAD

**Issue by somenxavier** [posativ/isso#200]
Hi,

I followed your quickstart guide but it seems that isso does not work. You could check it [here](http://somenxavier.xyz/prova.html).

My nginx config is:

```
server {
    listen 80;
    server_name comments.somenxavier.xyz;

    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

My isso config is:
```
[general]
dbpath = /var/isso/comments.db
host = http://somenxavier.xyz/
name = hola
[server]
listen = http://localhost:8080/
```

What is wrong?

Thanks in advance,

**Comment by sebix** [comment]
You use the domain name `comments.somenxavier.xyz`, but it does not exist in DNS.

**Comment by somenxavier** [comment]
Yes that was true. I registered new CNAME with comments and now I can access to `//comments.somenxavier.xyz/js/embed.min.js` but nothing else. I can't see any commenting interface [here](http://somenxavier.xyz/prova.html)

**Comment by somenxavier** [comment]
I found `GET 
http://comments.somenxavier.xyz/js/embed.min.js [HTTP/1.1 404 NOT FOUND 174ms]`

**Comment by somenxavier** [comment]
I installed the debian package and
```
root@deimos:/var/www/html/blog# dpkg  -L isso | grep min.js
/usr/lib/python2.7/dist-packages/isso/js/count.min.js
/usr/lib/python2.7/dist-packages/isso/js/embed.min.js
```

**Comment by posativ** [comment]
You are using multi-site, either use your URL + "/hola" or the single-site variant.

**Comment by somenxavier** [comment]
Single site

**Comment by somenxavier** [comment]
Running isso [at raw](https://github.com/posativ/isso/issues/200#issuecomment-137390589), I get 502 error at nginx:
```
79.146.236.35 - - [03/Sep/2015:11:38:36 +0200] "GET /js/embed.min.js HTTP/1.1" 502 166 "http://somenxavier.xyz/prova.html" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0"
```

**Comment by posativ** [comment]
Your systemd service runs `isso.dispatch`, you should use `isso.run`.

**Comment by somenxavier** [comment]
@posativ : thanks I will solve that. But with the `$ isso -c /path/to/isso.cfg run` it does not work neither.

**Comment by posativ** [comment]
If you use `isso -c my.conf run`, your nginx configuration is wrong. Your configuration runs on port 8080, but your nginx conf uses 8000.

**Comment by somenxavier** [comment]
@posativ: Thanks a lot. Now I get 200 (OK):
```
85.119.199.3 - - [03/Sep/2015:18:53:02 +0200] "GET /prova.html HTTP/1.0" 200 344 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0"
85.119.199.3 - - [03/Sep/2015:18:53:02 +0200] "GET /js/embed.min.js HTTP/1.0" 200 41388 "http://somenxavier.xyz/prova.html" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0"
```

but I can't get nothing in the [page](http://somenxavier.xyz/prova.html).... What happens now?

**Comment by somenxavier** [comment]
Now: `ReferenceError: exports is not defined` in firefox console

**Comment by somenxavier** [comment]
Anyone could see the `ReferenceError` error? Thanks a lot,

**Comment by somenxavier** [comment]
Anyone?

**Comment by Iota1** [comment]
I ran into the same error with the Debian package. A solution that worked for me was to install using pip into a virtualenv.

**Comment by somenxavier** [comment]
So, what's the difference between that? Can we file bug in debian?

**Comment by somenxavier** [comment]
With pip I just can't compile it:
```
(isso)xan@deimos:~$ cat /home/xan/.pip/pip.log 
Downloading/unpacking isso
  Getting page https://pypi.python.org/simple/isso/
  URLs to search for versions for isso:
  * https://pypi.python.org/simple/isso/
  Analyzing links from page https://pypi.python.org/simple/isso/
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.8.1.tar.gz#md5=b2a9150d3864db1984071294d7912d74 (from https://pypi.python.org/simple/isso/), version: 0.8.1
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.8.2.tar.gz#md5=cfbf2fe9a4faf740c2a398c0febd284c (from https://pypi.python.org/simple/isso/), version: 0.8.2
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.8.3.tar.gz#md5=424ca0ebdc27e0d50424211371259e7e (from https://pypi.python.org/simple/isso/), version: 0.8.3
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.8.tar.gz#md5=1a5ad2b9ea79b901f2d2997e06053494 (from https://pypi.python.org/simple/isso/), version: 0.8
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.1.tar.gz#md5=3286ab522d6349b7741c55ec6d2c3cbf (from https://pypi.python.org/simple/isso/), version: 0.9.1
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.10.tar.gz#md5=7f76f892e85a2465425b4030af1bffe9 (from https://pypi.python.org/simple/isso/), version: 0.9.10
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.2.tar.gz#md5=a28413a80cce52cf93c4c9c9421ff9f5 (from https://pypi.python.org/simple/isso/), version: 0.9.2
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.3.tar.gz#md5=2e809feb16e69b3fd07b377e5af2a268 (from https://pypi.python.org/simple/isso/), version: 0.9.3
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.4.tar.gz#md5=679dfb30f2f0cca316e7c1ec57093673 (from https://pypi.python.org/simple/isso/), version: 0.9.4
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.5.tar.gz#md5=fd46c028aee2d11246e5f28bcfc1c6e6 (from https://pypi.python.org/simple/isso/), version: 0.9.5
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.6.tar.gz#md5=73f1fca952b87b5500a68faa03b16240 (from https://pypi.python.org/simple/isso/), version: 0.9.6
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.7.tar.gz#md5=22a821bb22661b4ebf8841ea6e1de60d (from https://pypi.python.org/simple/isso/), version: 0.9.7
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.8.tar.gz#md5=536887ae596123c8396cb45fae0b7e88 (from https://pypi.python.org/simple/isso/), version: 0.9.8
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.9.tar.gz#md5=3f740572f7d2abeb3d50d105be7139e8 (from https://pypi.python.org/simple/isso/), version: 0.9.9
    Found link https://pypi.python.org/packages/source/i/isso/isso-0.9.tar.gz#md5=743d50a3115fba8a3e6c16bf0fb42db8 (from https://pypi.python.org/simple/isso/), version: 0.9
  Using version 0.9.10 (newest of versions: 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9, 0.8.3, 0.8.2, 0.8.1, 0.8)
  Downloading from URL https://pypi.python.org/packages/source/i/isso/isso-0.9.10.tar.gz#md5=7f76f892e85a2465425b4030af1bffe9 (from https://pypi.python.org/simple/isso/)
  Running setup.py (path:/tmp/pip-build-M5AZG4/isso/setup.py) egg_info for package isso
    running egg_info
    creating pip-egg-info/isso.egg-info
    writing requirements to pip-egg-info/isso.egg-info/requires.txt
    writing pip-egg-info/isso.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/isso.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/isso.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/isso.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/isso.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/isso.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/isso.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-M5AZG4/isso has version 0.9.10, which satisfies requirement isso
Downloading/unpacking itsdangerous (from isso)
  Getting page https://pypi.python.org/simple/itsdangerous/
  URLs to search for versions for itsdangerous (from isso):
  * https://pypi.python.org/simple/itsdangerous/
  Analyzing links from page https://pypi.python.org/simple/itsdangerous/
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.10.tar.gz#md5=5ec216aac82761339a7599ef98b47914 (from https://pypi.python.org/simple/itsdangerous/), version: 0.10
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.11.tar.gz#md5=2bd23801f051c344bc5f06e673b8d1e0 (from https://pypi.python.org/simple/itsdangerous/), version: 0.11
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.12.tar.gz#md5=a83dbd4f42d284d497c0bc247ac04509 (from https://pypi.python.org/simple/itsdangerous/), version: 0.12
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.13.tar.gz#md5=d13b58d1ee2ef9e1f95d9133e7ecb4bf (from https://pypi.python.org/simple/itsdangerous/), version: 0.13
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.14.tar.gz#md5=128e0a26a75e6640350749162697ffa3 (from https://pypi.python.org/simple/itsdangerous/), version: 0.14
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.15.tar.gz#md5=f4125355528979570ec4ef18a64d000d (from https://pypi.python.org/simple/itsdangerous/), version: 0.15
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.16.tar.gz#md5=42f9a6d1c6727c6221207d96c9621b76 (from https://pypi.python.org/simple/itsdangerous/), version: 0.16
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.17.tar.gz#md5=f40c7dc39beb859988b0a801d13672aa (from https://pypi.python.org/simple/itsdangerous/), version: 0.17
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.18.tar.gz#md5=2549de4c366cd48ab0f9d32f363833e8 (from https://pypi.python.org/simple/itsdangerous/), version: 0.18
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.19.tar.gz#md5=0eb918080911b0829e1df36a513b48d5 (from https://pypi.python.org/simple/itsdangerous/), version: 0.19
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.20.tar.gz#md5=adb4f7e4dd5f717341384837ca058c9c (from https://pypi.python.org/simple/itsdangerous/), version: 0.20
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.21.tar.gz#md5=84d4b33f0a1e4d0f7f8f8755a5eb2580 (from https://pypi.python.org/simple/itsdangerous/), version: 0.21
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.22.tar.gz#md5=ba715357eadfb045ca06e11869366bfd (from https://pypi.python.org/simple/itsdangerous/), version: 0.22
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.23.tar.gz#md5=985e726eb76f18aca81e703f0a6c6efc (from https://pypi.python.org/simple/itsdangerous/), version: 0.23
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.24.tar.gz#md5=a3d55aa79369aef5345c036a8a26307f (from https://pypi.python.org/simple/itsdangerous/), version: 0.24
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.9.1.tar.gz#md5=906506f36c4332059ba37b874da88d48 (from https://pypi.python.org/simple/itsdangerous/), version: 0.9.1
    Found link https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.9.tar.gz#md5=36e0a40eb98e3b48fa37039617d1cd2b (from https://pypi.python.org/simple/itsdangerous/), version: 0.9
  Using version 0.24 (newest of versions: 0.24, 0.23, 0.22, 0.21, 0.20, 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.10, 0.9.1, 0.9)
  Downloading from URL https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.24.tar.gz#md5=a3d55aa79369aef5345c036a8a26307f (from https://pypi.python.org/simple/itsdangerous/)
  Running setup.py (path:/tmp/pip-build-M5AZG4/itsdangerous/setup.py) egg_info for package itsdangerous
    running egg_info
    creating pip-egg-info/itsdangerous.egg-info
    writing pip-egg-info/itsdangerous.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/itsdangerous.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/itsdangerous.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/itsdangerous.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/itsdangerous.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    writing manifest file 'pip-egg-info/itsdangerous.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-M5AZG4/itsdangerous has version 0.24, which satisfies requirement itsdangerous (from isso)
Downloading/unpacking misaka (from isso)
  Getting page https://pypi.python.org/simple/misaka/
  URLs to search for versions for misaka (from isso):
  * https://pypi.python.org/simple/misaka/
  Analyzing links from page https://pypi.python.org/simple/misaka/
    Skipping link https://pypi.python.org/packages/2.7/m/misaka/misaka-0.4.1.win32-py2.7.msi#md5=d4c2881fda254cfa10086b1e7852332b (from https://pypi.python.org/simple/misaka/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/3.2/m/misaka/misaka-0.4.1.win32-py3.2.msi#md5=2c99bf3926a1c768a66d5b52084923ba (from https://pypi.python.org/simple/misaka/); unknown archive format: .msi
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-0.3.1.tar.gz#md5=ecc32e5831ceae4f623c8ba05a19ca19 (from https://pypi.python.org/simple/misaka/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-0.3.2.tar.gz#md5=b0633f674e38ff06a9e3c590c18f09aa (from https://pypi.python.org/simple/misaka/), version: 0.3.2
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-0.3.3.tar.gz#md5=b0197bc1148cc514f77b1a9a55118554 (from https://pypi.python.org/simple/misaka/), version: 0.3.3
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-0.4.0.tar.gz#md5=efe325118a4311f7f9118d3343ee9827 (from https://pypi.python.org/simple/misaka/), version: 0.4.0
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-0.4.1.tar.gz#md5=b84983f505d16d3b930c7c15dde6f72c (from https://pypi.python.org/simple/misaka/), version: 0.4.1
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-0.4.2.tar.gz#md5=e5991485d01128a0296159f43d899660 (from https://pypi.python.org/simple/misaka/), version: 0.4.2
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-1.0.0.tar.gz#md5=7462b5902f1da09000f8c0a654ea3ae9 (from https://pypi.python.org/simple/misaka/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-1.0.1.tar.gz#md5=7d5ea01ceda8ad84ff09a31a3e61a7c8 (from https://pypi.python.org/simple/misaka/), version: 1.0.1
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-1.0.2.tar.gz#md5=e99649aaa2a1d0dbeec78069fee3551a (from https://pypi.python.org/simple/misaka/), version: 1.0.2
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-2.0.0.tar.gz#md5=79352edb71f604402277d8bb6d3a54ef (from https://pypi.python.org/simple/misaka/), version: 2.0.0
    Found link https://pypi.python.org/packages/source/m/misaka/misaka-2.0.0b1.post2.tar.gz#md5=b6ba34a1ff120d475227ea3d944076e2 (from https://pypi.python.org/simple/misaka/), version: 2.0.0b1.post2
    Skipping link http://misaka.61924.nl/ (from https://pypi.python.org/simple/misaka/); not a file
    Skipping link https://github.com/tanoku/sundown (from https://pypi.python.org/simple/misaka/); not a file
    Skipping link https://github.com/tanoku/upskirt (from https://pypi.python.org/simple/misaka/); not a file
  Ignoring link https://pypi.python.org/packages/source/m/misaka/misaka-2.0.0b1.post2.tar.gz#md5=b6ba34a1ff120d475227ea3d944076e2 (from https://pypi.python.org/simple/misaka/), version 2.0.0b1.post2 is a pre-release (use --pre to allow).
  Using version 2.0.0 (newest of versions: 2.0.0, 1.0.2, 1.0.1, 1.0.0, 0.4.2, 0.4.1, 0.4.0, 0.3.3, 0.3.2, 0.3.1)
  Downloading from URL https://pypi.python.org/packages/source/m/misaka/misaka-2.0.0.tar.gz#md5=79352edb71f604402277d8bb6d3a54ef (from https://pypi.python.org/simple/misaka/)
  Running setup.py (path:/tmp/pip-build-M5AZG4/misaka/setup.py) egg_info for package misaka
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-M5AZG4/misaka/setup.py", line 68, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in best_match
        return self.obtain(req, installer)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pkg_resources.py", line 886, in obtain
        return installer(requirement)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 636, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 856, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1066, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory

 #include <ffi.h>

                 ^

compilation terminated.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-M5AZG4/misaka/setup.py", line 68, in <module>

    cffi_modules=['build_ffi.py:ffi'],

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/dist.py", line 262, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs

    replace_conflicting=True,

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in best_match

    return self.obtain(req, installer)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pkg_resources.py", line 886, in obtain

    return installer(requirement)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in fetch_build_egg

    return cmd.easy_install(req)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 636, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 856, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1078, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1066, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-M5AZG4/misaka
Exception information:
Traceback (most recent call last):
  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/xan/pypi/isso/local/lib/python2.7/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-M5AZG4/misaka
(isso)xan@deimos:~$

```

**Comment by somenxavier** [comment]
I'm trying now with `debian-isso`. But I have [some problems](https://github.com/jgraichen/debian-isso/issues/10).

**Comment by somenxavier** [comment]
It works [now](somenxavier.xyz/prova.html) with [debian-isso](https://github.com/jgraichen/debian-isso/issues/10?_pjax=%23js-repo-pjax-container) installation
