### ISSUE TITLE
Error installing isso

### ISSUE THREAD

**Issue by harish211** [posativ/isso#216]
(c) C:\Users\Home\lib\c\tutorial>isso run
Traceback (most recent call last):
  File "C:\Users\Home\lib\c\Scripts\isso-script.py", line 9, in <module>
    load_entry_point('isso==0.10.dev0', 'console_scripts', 'isso')()
  File "C:\Users\Home\lib\c\lib\site-packages\isso\__init__.py", line 226, in main
    conf = config.load(join(dist.location, "share", "isso.conf"), args.conf)
  File "C:\Users\Home\lib\c\lib\site-packages\isso\config.py", line 152, in load
    if not parseaddr(parser.get("smtp", "from"))[0]:
  File "C:\Users\Home\lib\c\lib\site-packages\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Home\lib\c\lib\site-packages\configparser.py", line 1177, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: u'smtp'

**Comment by posativ** [comment]
The path to the default configuration (in `site-packages/isso/share/isso.conf`) does not exist. The main developer (me) doesn't use Windows and I can't support this platform really, as Isso is intended for lightweight self-hosting (uncommon for Windows Server).
