### ISSUE TITLE
Can't publish message (Markdown can't render)

### ISSUE THREAD

**Issue by floreal** [posativ/isso#230]
Hello,
I installed isso on my production server, and I got that kind of message in my log:
```
2016-01-27 14:12:31,052 ERROR: GET /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/isso/__init__.py", line 136, in dispatch
    response = handler(request.environ, request, **values)
  File "/usr/local/lib/python2.7/dist-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/isso/views/comments.py", line 421, in fetch
    'replies'        : self._process_fetched_list(root_list, plain)
  File "/usr/local/lib/python2.7/dist-packages/isso/views/comments.py", line 464, in _process_fetched_list
    item['text'] = self.isso.render(item['text'])
  File "/usr/local/lib/python2.7/dist-packages/isso/__init__.py", line 114, in render
    return self.markup.render(text)
  File "/usr/local/lib/python2.7/dist-packages/isso/utils/html.py", line 102, in render
    return self._render(text)
  File "/usr/local/lib/python2.7/dist-packages/isso/utils/html.py", line 99, in <lambda>
    self._render = lambda text: sanitize(sanitizer, parser(text))
  File "/usr/local/lib/python2.7/dist-packages/isso/utils/html.py", line 69, in inner
    rv = md.render(text).rstrip("\n")
AttributeError: 'Markdown' object has no attribute 'render'
2016-01-27 14:13:10,464 ERROR: POST /new
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/isso/__init__.py", line 136, in dispatch
    response = handler(request.environ, request, **values)
  File "/usr/local/lib/python2.7/dist-packages/isso/views/comments.py", line 84, in dec
    return func(self, env, req, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/isso/views/comments.py", line 221, in new
    rv["text"] = self.isso.render(rv["text"])
  File "/usr/local/lib/python2.7/dist-packages/isso/__init__.py", line 114, in render
    return self.markup.render(text)
  File "/usr/local/lib/python2.7/dist-packages/isso/utils/html.py", line 102, in render
    return self._render(text)
  File "/usr/local/lib/python2.7/dist-packages/isso/utils/html.py", line 99, in <lambda>
    self._render = lambda text: sanitize(sanitizer, parser(text))
  File "/usr/local/lib/python2.7/dist-packages/isso/utils/html.py", line 69, in inner
    rv = md.render(text).rstrip("\n")
AttributeError: 'Markdown' object has no attribute 'render'
```

I'm using python 2.7 on raspbian.
What can I do to fix this

**Comment by smileboywtu** [comment]
check the version of misaka, only support 1.0.2

**Comment by floreal** [comment]
Ok i'll try to downgrade it to version 1.0.2, it's 2.0.0, right now

**Comment by floreal** [comment]
Problem fixed downgrading misaka version, thanks
