### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by 22decembre** [posativ/isso#278]
Sorry, I don't know how to report that correctly, as I don't know what is the actual trouble.

I installed isso using virtualenv in the chroot of my webserver (httpd/openbsd 6.0).

The chroot and relevant repositories inside :

```
/var/www/  
/var/www/isso/bin/isso  
/var/www/isso/lib... etc
/var/www/isso/js  
/var/www/tmp/isso.sock
/var/www/pelican
```

I get javascript working on the pages, but receiving the comments, no, that won't work now.

Here is the bug appearing in the logs, or when I launch isso in the command line :

```
Exception happened during processing of request from  
Traceback (most recent call last):  
 File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock  
self.process_request(request, client_address)  
 File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request  
self.finish_request(request, client_address)
 File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/var/www/isso/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/var/www/isso/lib/python2.7/site-packages/werkzeug/serving.py", line 250, in handle_one_request
    elif self.parse_request():
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/var/www/isso/lib/python2.7/site-packages/werkzeug/serving.py", line 275, in log_error
    self.log('error', *args)
  File "/var/www/isso/lib/python2.7/site-packages/werkzeug/serving.py", line 281, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/var/www/isso/lib/python2.7/site-packages/werkzeug/serving.py", line 266, in address_string
    return self.client_address[0]
IndexError: string index out of range
----------------------------------------
```

Now, I don't know what to do.

**Comment by posativ** [comment]
Hm, the issue is in a different layer (werkzeug -> HTTP/WSGI library). You are using a socket and somehow connecting to it, right? Does `listen = localhost:1234` work?

**Comment by 22decembre** [comment]
Yes, socket. And the webserver has it in its conf.

httpd.conf :
`location "/isso*" { fastcgi socket "/tmp/isso.sock" }`

isso.conf :
`listen = unix:///var/www/tmp/isso.sock`

`srwxr-xr-x  1 www   www        0 Sep 24 09:42 isso.sock`

**Comment by 22decembre** [comment]
I have just launched everything in command line with extra debugging for httpd.

When I request a webpage, the isso daemon shows the bug. Same when I submit a comment. So it looks like it listens on the socket. But httpd does not complain. Like everything is normal.

This is coherent with this: when requesting a webpage while the isso daemon is not up, httpd complains that a "/isso/count" is not present.

**Comment by posativ** [comment]
I have no OpenBSD at hands and my distribution does not package httpd. It will work with a networking interface like `lo`.

**Comment by ix5** [comment]
Unlikely to ever be verified.
