### ISSUE TITLE
mod_wsgi: no module named isso

### ISSUE THREAD

**Issue by hamoid** [posativ/isso#307]
Hi, I'm afraid I need some help. I spent several hours tweaking configurations and I can't make it work. To test permissions, I tried creating a file as `www-data` user inside the db folder and it worked fine. I'm using a virtual env at `/w/isso`, and isso 0.10.6 under Ubuntu 14.04

## The error in /var/log/apache2/error.log

```
...mod_wsgi (pid=5445): Exception occurred processing WSGI script '/w/isso/isso.wsgi'.
...Traceback (most recent call last):
...   File "/w/isso/isso.wsgi", line 18, in <module>
...     from isso import make_app
... ImportError: No module named isso

```

## /w/isso/isso.wsgi

```
import site
import sys

# Remember original sys.path.
prev_sys_path = list(sys.path)

# Add the new site-packages directory.
site.addsitedir("/w/isso")

# Reorder sys.path so new directories at the front.
new_sys_path = []
for item in list(sys.path):
    if item not in prev_sys_path:
        new_sys_path.append(item)
        sys.path.remove(item)
sys.path[:0] = new_sys_path

from isso import make_app
from isso.core import Config

application = make_app(Config.load("/w/isso/isso.cfg"))
```

## /etc/apache2/sites-enabled/www.x.conf

```
 <IfModule mod_ssl.c>
 <VirtualHost *:443>
     ServerAdmin webmaster@localhost
     ServerName www.x.org
     ServerAlias x.org
 
     DocumentRoot /w/x.org
     <Directory />
         Options FollowSymLinks
         AllowOverride None
     </Directory>
     <Directory /w/x.org/>
         Options FollowSymLinks MultiViews
         AllowOverride all
         Order allow,deny
         allow from all
     </Directory>
 
     ErrorLog /var/log/apache2/x.log 
     LogLevel info
     CustomLog /var/log/apache2/x.log combined
 
     WSGIApplicationGroup %{GLOBAL}
     WSGIScriptAlias /isso /w/isso/isso.wsgi
     # process-group=isso-x application-group=%{GLOBAL}
     WSGIDaemonProcess isso-x user=www-data group=www-data threads=5
     WSGIProcessGroup isso-x
 
     <Directory /w/isso>
         Order allow,deny
         Allow from all
     </Directory>

     <IfModule mod_proxy.c> 
         ProxyVia On
         ProxyRequests Off
         ProxyPass /something/ http://www.x.org:9001/
         ProxyPassReverse /something/ http://www.x.org:9001/
         ProxyPreserveHost on
         <Proxy *>
             Options FollowSymLinks MultiViews
             AllowOverride All
             Require all granted
         </Proxy>
     </IfModule>

     SSLCertificateFile /etc/letsencrypt/live/x.org/cert.pem
     SSLCertificateKeyFile /etc/letsencrypt/live/x.org/privkey.pem
     Include /etc/letsencrypt/options-ssl-apache.conf
     SSLCertificateChainFile /etc/letsencrypt/live/x.org/chain.pem
 </VirtualHost>
 </IfModule>
```

Do I need to adjust my firewall? How is Apache going to connect with isso? Without mod_wsgi I've seen there's a http port, but I haven't seen that with mod_wsgi. Or is it sockets? Thank you in advance!

**Comment by hamoid** [comment]
Following http://www.thecodeship.com/deployment/deploy-django-apache-virtualenv-and-mod_wsgi/ I changed isso.wsgi like this:

    site.addsitedir("/w/isso/lib/python2.7/site-packages")
    ...
    activate_env = "/w/isso/bin/activate_this.py"
    execfile(activate_env, dict(__file__=activate_env))

Not sure if that's progress or not, but the error is now different:

```
mod_wsgi (pid=23164): Target WSGI script '/w/isso/isso.wsgi' cannot be loaded as Python module.
 mod_wsgi (pid=23164): Exception occurred processing WSGI script '/w/isso/isso.wsgi'.
 Traceback (most recent call last):
   File "/w/isso/isso.wsgi", line 22, in <module>
     from isso.core import Config
 ImportError: cannot import name Config
```

Why does `from isso.core import Config` fail now?

**Comment by hamoid** [comment]
Not giving up... My .wsgi file now looks like this:

```
import site
import sys

# Remember original sys.path.
prev_sys_path = list(sys.path)

# Add the new site-packages directory.
site.addsitedir("/w/isso/lib/python2.7/site-packages")

# Reorder sys.path so new directories at the front.
new_sys_path = []
for item in list(sys.path):
    if item not in prev_sys_path:
        new_sys_path.append(item)
        sys.path.remove(item)
sys.path[:0] = new_sys_path

activate_env = "/w/isso/bin/activate_this.py"
execfile(activate_env, dict(__file__=activate_env))

from isso import make_app
from isso import config

application = make_app(config.load("/w/isso/isso.cfg"))
```

This gave me errors of missing configuration settings, which I believe it might be because it doesn't find the default settings. So I added every single server setting to my .cfg file and finally it starts. I see the comments form. 

Next error: it complains about `attempt to write a readonly database`.

The /w/isso/ folder is owned by www-data, 775 and the db also owned by www-data and is 644. The Apache file contains `WSGIDaemonProcess isso-x user=www-data group=www-data threads=5` and I tested that files can be created in the /w/isso folder by user www-data. Maybe the process is not run by www-data?

**Comment by hamoid** [comment]
I think I got it working. I don't know why so many changes were necessary compared to the isso documentation.

## www.site.conf

     WSGIScriptAlias /isso /w/isso/isso.wsgi 
     WSGIDaemonProcess isso-x threads=5 home=/w/isso/ 
     WSGIProcessGroup isso-x

I'm running this site on ssl. I have ServerName with www and a ServerAlias without www. To make it work I had to redirect all requests to the www site on https like this:

    RewriteEngine On
    RewriteCond %{HTTP_HOST} ^x.org
    RewriteRule (.*) https://www.x.org/$1 [R=301,L]

## isso.wsgi

```
import site
import sys

# Remember original sys.path.
prev_sys_path = list(sys.path)

# Add the new site-packages directory.
site.addsitedir("/w/isso/lib/python2.7/site-packages")

# Reorder sys.path so new directories at the front.
new_sys_path = []
for item in list(sys.path):
    if item not in prev_sys_path:
        new_sys_path.append(item)
        sys.path.remove(item)
sys.path[:0] = new_sys_path

activate_env = "/w/isso/bin/activate_this.py"
execfile(activate_env, dict(__file__=activate_env))

from isso import make_app
from isso import config

application = make_app(config.load("/w/isso/isso.cfg"))
```

## isso.cfg

```
[general]
 dbpath = /w/isso/x.db
 host = 
     https://www.x.org/
     https://x.org/
 notify = smtp
 max-age = 15m
 
 [smtp]
 username = comments@x.org
 password = ababababababababa
 host = localhost
 port = 587
 security = starttls
 to = fun@x.org
 from = "X X" <comments@x.org>
 timeout = 10
 
 [moderation]
 enabled = true
 purge-after = 30d
 
 [server]
 listen = http://localhost:8080
 reload = off
 profile = off
 
 [guard]
 enabled = true
 ratelimit = 2
 direct-reply = 3
 reply-to-self = true
 require-author = true
 require-email = false
 
 [markup]
 options = strikethrough, superscript, autolink
 allowed-elements = a, blockquote, br, code, del, img, em, h1, h2, h3, h4, h5, h6,   hr, ins, li, ol, p, pre, strong, table, tbody, td, th, thead and ul
 allowed-attributes = align, href, src
 
 [hash]
 salt = xxxxxxxxxxxxxx
 algorithm = pbkdf2
```

**Comment by jelmer** [comment]
Pity you had such a bad experience. :( It looks like this what you had trouble with is the combination of wsgi and virtualenv, rather than anything specific to isso.

**Comment by blatinier** [comment]
@hamoid Since you got it working I close the issue. I hope you got a better experience since then :)

**Comment by hamoid** [comment]
Thanks. I haven't touched it and it's still running :) I'm looking forward to future releases!
