### ISSUE TITLE
After running isso, meet TypeError: must be string without null bytes, not str

### ISSUE THREAD

**Issue by StinsonZhao** [posativ/isso#309]
The console output is : 
```
isso -c /opt/isso/isso.conf run
2017-03-14 18:16:15,926 INFO: connected to https://localhost/
Traceback (most recent call last):
  File "/usr/local/bin/isso", line 9, in <module>
    load_entry_point('isso==0.10.6', 'console_scripts', 'isso')()
  File "/opt/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 270, in main
    wsgi.SocketHTTPServer(sock, make_app(conf)).serve_forever()
  File "/opt/isso/local/lib/python2.7/site-packages/isso/wsgi.py", line 203, in __init__
    HTTPServer.__init__(self, sock, SocketWSGIRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 110, in server_bind
    self.server_name = socket.getfqdn(host)
  File "/usr/lib/python2.7/socket.py", line 137, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
TypeError: must be string without null bytes, not str
```

what happened? thanks

**Comment by ix5** [comment]
Could you please supply more information?
Also, does this issue still occur on python 3?
