### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by skorokithakis** [posativ/isso#388]
Is there going to be a new release soon? The last one was in 2016, and I see there have been a bunch of improvements since.

**Comment by blatinier** [comment]
I pinged @posativ in #382 about it, but no answer yet. He is very busy and that's why @jelmer and I had write access to the repo, but only @posativ can release.
So for now no release planned, no date to communicate. In the mean time you can clone the master branch or using pip: `pip install git+git://github.com/jkbr/httpie.git` (Yes I know it does not solve the problem)

**Comment by skorokithakis** [comment]
Ah, thank you. Is master stable enough for production use?

**Comment by blatinier** [comment]
The current HEAD is stable. But if you plan to do some `pip update` regularly it may break even though we are careful about that when merging to master.

**Comment by skorokithakis** [comment]
Ah, I'll pin to the latest commit then, thank you.

**Comment by blatinier** [comment]
Ok, I'll close this and try to ping @posativ more privately for a release.

**Comment by skorokithakis** [comment]
@blatinier Unfortunately, the latest HEAD doesn't work for me. It had problems parsing the `defaults.ini` (it's not an actual ini file) and, for some reason, `embed.min.js` cannot be found either. Now my comments aren't showing at all.

**Comment by blatinier** [comment]
Can you provide us with some stacktrace and the default.ini file maybe.
Did you build the javascript files using `make js`?

**Comment by skorokithakis** [comment]
Here's the traceback:

```
root@32e270eae1a0:/code# isso
Traceback (most recent call last):
  File "/usr/local/bin/isso", line 11, in <module>
    load_entry_point('isso==0.10.7.dev0', 'console_scripts', 'isso')()
  File "/usr/local/lib/python3.6/site-packages/isso/__init__.py", line 234, in main
    join(dist.location, dist.project_name, "defaults.ini"), args.conf)
  File "/usr/local/lib/python3.6/site-packages/isso/config.py", line 130, in load
    parser.read(default)
  File "/usr/local/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/usr/local/lib/python3.6/site-packages/isso/defaults.ini', line: 1
'../share/isso.conf'
```

Here's a Dockerfile that reproduces this:

```
FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN pip install -U pip pipenv
ADD Pipfile* /code/

WORKDIR /code
COPY . /code/
RUN pipenv install --system
```

The file I install from is https://github.com/posativ/isso/archive/0ff39017c6fab706a5e616f2a9a8645603ee4698.zip

I didn't run make.js, at which point after the `pip install` do I need to do that?

**Comment by blatinier** [comment]
You should run isso with a proper config file (using `-c` option).
See https://posativ.org/isso/docs/quickstart/#running-isso for running command.
See https://posativ.org/isso/docs/quickstart/#configuration for basic configuration and https://posativ.org/isso/docs/configuration/server/ for more details.

Tell me if you have more problems after that.

**Comment by skorokithakis** [comment]
Yep, same traceback, I just forgot to include it in the command line:

```
root@27f5233d847c:/code# isso -c isso.cfg 
Traceback (most recent call last):
  File "/usr/local/bin/isso", line 11, in <module>
    load_entry_point('isso==0.10.7.dev0', 'console_scripts', 'isso')()
  File "/usr/local/lib/python3.6/site-packages/isso/__init__.py", line 234, in main
    join(dist.location, dist.project_name, "defaults.ini"), args.conf)
  File "/usr/local/lib/python3.6/site-packages/isso/config.py", line 130, in load
    parser.read(default)
  File "/usr/local/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/usr/local/lib/python3.6/site-packages/isso/defaults.ini', line: 1
'../share/isso.conf'
```

The config file is:

```ini
[general]
dbpath = /data/comments.db
notify = smtp
admin_password = password
host =
    https://www.example.com/

[guard]
require-author = True
ratelimit = 10
direct-reply = 200

[server]
listen = http://0.0.0.0:5000/

[smtp]
username = SMTP_Injection
password = password
host = smtp.example.com
port = 587
security = starttls
to = email@example.com
from = email@example.com
timeout = 30
```

**Comment by blatinier** [comment]
It doesn't seem to use your config file but the default.ini file. Try providing the absolute path to your config file.

**Comment by blatinier** [comment]
You should run isso with a proper config file (using `-c` option).
See https://posativ.org/isso/docs/quickstart/#running-isso for running command.
See https://posativ.org/isso/docs/quickstart/#configuration for basic configuration and https://posativ.org/isso/docs/configuration/server/ for more details.

Tell me if you have more problems after that.

**Comment by skorokithakis** [comment]
Same problem:

```
root@8c08898214fb:/code# isso -c /code/isso.cfg 
Traceback (most recent call last):
  File "/usr/local/bin/isso", line 11, in <module>
    load_entry_point('isso==0.10.7.dev0', 'console_scripts', 'isso')()
  File "/usr/local/lib/python3.6/site-packages/isso/__init__.py", line 234, in main
    join(dist.location, dist.project_name, "defaults.ini"), args.conf)
  File "/usr/local/lib/python3.6/site-packages/isso/config.py", line 130, in load
    parser.read(default)
  File "/usr/local/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/usr/local/lib/python3.6/site-packages/isso/defaults.ini', line: 1
'../share/isso.conf'
```

You can just run the Docker script to see for yourself, btw, it reproduces pretty reliably.

**Comment by blatinier** [comment]
I did it and it works for me:

     docker build . -t isso:skorokithakis
     docker run -i --rm isso:skorokithakis

Then inside the container:

    pip install .
    cp share/isso-dev.conf .  # copy the dev (same used for Vagrant) conf
    sed -i -e"s/\/var\/isso\/comments.db/\/code\/comments.db/" isso-dev.conf  # modify the db path to point inside a writable place in the container (DO NOT DO THAT IN REAL LIFE, DATA INSIDE A CONTAINER IS EPHEMERAL)
    isso -c isso-dev.conf  # run isso, it works...

I'm currently working on a Docker/docker-compose easy setup that I will commit soon (I hope)
