### ISSUE TITLE
I cannot use misaka math extension

### ISSUE THREAD

**Issue by somenxavier** [posativ/isso#396]
```
isso) root@fobos:/home/xan# Traceback (most recent call last):
  File "/opt/isso/bin/isso", line 11, in <module>
    sys.exit(main())
  File "/opt/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 261, in main
    run_simple(host, port, make_app(conf), threaded=True,
  File "/opt/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 167, in make_app
    isso = App(conf)
  File "/opt/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 91, in __init__
    self.markup = html.Markup(conf.section('markup'))
  File "/opt/isso/local/lib/python2.7/site-packages/isso/utils/html.py", line 94, in __init__
    parser = Markdown(conf.getlist("options"))
  File "/opt/isso/local/lib/python2.7/site-packages/isso/utils/html.py", line 65, in Markdown
    lambda ext: getattr(misaka, 'EXT_' + ext.upper()), extensions), 0)
  File "/opt/isso/local/lib/python2.7/site-packages/isso/utils/html.py", line 65, in <lambda>
    lambda ext: getattr(misaka, 'EXT_' + ext.upper()), extensions), 0)
AttributeError: 'module' object has no attribute 'EXT_MATH'
```

Perhaps it is because isso needs misaka 1.0.2 and latest misaka is 2.1.0? Extension `math-explicit` (`math_explicit`) does not work too

**Comment by blatinier** [comment]
I just merged the PR to upgrade misaka to it's version >2. Could you test again?

**Comment by somenxavier** [comment]
@blatinier How can I do that? I installed via `pip` Did you upgrade pip version?

**Comment by blatinier** [comment]
Pip version has not been upgraded lately. You should install from source. 
Clone the branch master of this repository and install it using these instructions: https://posativ.org/isso/docs/install/#install-from-source

**Comment by somenxavier** [comment]
I'm in production. I'd prefer to wait until pip version is uptodate

On Tue, 01 May 2018 14:38:05 -0700
Benoît Latinier <notifications@github.com> ha escrit:

**Comment by blatinier** [comment]
Pip version is probably going to stale for a moment. Posativ has not enough time for publishing so since it's OK in master I close.

**Comment by somenxavier** [comment]
A pain
