### ISSUE TITLE
no module names isso.dispatch

### ISSUE THREAD

**Issue by kurt-o-sys** [posativ/isso#453]
I'm trying to setup isso and gunicorn for a multi blogs. I followed the installation guide and took some ideas from https://fralef.me/configure-isso-to-work-with-multiple-sites-using-gunicorn-and-nginx.html .
I'm not yet at configuring nginx - that will be ok - but starting gunicorn already fails:
```
$ gunicorn isso.dispatch -b localhost:2323
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==19.6.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 61, in __init__
    self.setup(app)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 384, in import_app
    __import__(module)
ImportError: No module named isso.dispatch
``` 

So, I'm missing some module (although I did install isso, at least, I suppose so).

What am I doing wrong?

**Comment by kurt-o-sys** [comment]
oh... when I start it after I run `source /opt/isso/bin/activate`, it does work... This means, the question now is: how can I make it run from outside the virtual environment? (I want to add it to a systemd service-script)

**Comment by kurt-o-sys** [comment]
... got it, apparently, I had the wrong gunicorn: `/usr/bin/gunicorn`. I needed to point to `/opt/isso/bin/gunicorn`.
