### ISSUE TITLE
Misaka: expected bytes, got buffer

### ISSUE THREAD

**Issue by hamoid** [posativ/isso#474]
Why can this happen?
```
2018-08-12 17:52:08,035 ERROR: GET /
Traceback (most recent call last):
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 135, in dispatch
    response = handler(request.environ, request, **values)
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/views/comments.py", line 426, in fetch
    comment['replies'] = self._process_fetched_list(replies, plain)
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/views/comments.py", line 447, in _process_fetched_list
    item['text'] = self.isso.render(item['text'])
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 113, in render
    return self.markup.render(text)
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/utils/html.py", line 102, in render
    return self._render(text)
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/utils/html.py", line 99, in <lambda>
    self._render = lambda text: sanitize(sanitizer, parser(text))
  File "/home/abe/isso/local/lib/python2.7/site-packages/isso/utils/html.py", line 69, in inner
    rv = md.render(text).rstrip("\n")
  File "misaka.pyx", line 220, in misaka.Markdown.render (src/misaka.c:1681)
TypeError: Expected bytes, got buffer
```

When it happens: things are working fine. I edit one comment with sqlite3 to add code fences. Then, when I reload the page, I get that error. The only difference is the opening and ending code fences around some code.

I'm running the last published version, since I didn't manage to make the one from GitHub work. https://github.com/posativ/isso/issues/464

**Comment by jelmer** [comment]
can you try the latest version? There have been a lot of changes since.
