### ISSUE TITLE
uWSGI sendmail for admin notification: NoneType has no attribute encode

### ISSUE THREAD

**Issue by RedFlames** [posativ/isso#578]
hi!

I have started using isso on an uberspace hugo site, and just tried to switch it over from gevent to uwsgi.

I also tried enabling moderation emails. This is where uwsgi started giving me this error:
```
2019-10-29 13:45:42,065 ERROR: POST /new
Traceback (most recent call last):
  File "<venv-path-blah-blah>/python3.6/site-packages/isso/__init__.py", line 141, in dispatch
    response = handler(request.environ, request, **values)
  File "<venv-path-blah-blah>/python3.6/site-packages/isso/views/comments.py", line 92, in dec
    return func(self, env, req, *args, **kwargs)
  File "<venv-path-blah-blah>/python3.6/site-packages/isso/views/__init__.py", line 46, in dec
    return func(cls, env, req, *args, **kwargs)
  File "<venv-path-blah-blah>/python3.6/site-packages/isso/views/comments.py", line 299, in new
    self.signal("comments.new:after-save", thread, rv)
  File "<venv-path-blah-blah>/python3.6/site-packages/isso/ext/__init__.py", line 17, in __call__
    subscriber(*args, **kwargs)
  File "<venv-path-blah-blah>/python3.6/site-packages/isso/ext/notifications.py", line 152, in notify_new
    self.sendmail(thread["title"], body, thread, comment)
  File "<venv-path-blah-blah>/python3.6/site-packages/isso/ext/notifications.py", line 179, in sendmail
    uwsgi.spool({b"subject": subject.encode("utf-8"),
AttributeError: 'NoneType' object has no attribute 'encode'
```

I edited that python file and put a logging output in `notify_new`, and:
```
{'id': 1, 'uri': '/blog/post/hello-world/', 'title': None}
```
sure enough, title is `None`, which becomes the subject for the mail. And then encode fails.

My hack-y fix right now was to add at around [line 177](https://github.com/posativ/isso/blob/c24ee69a1e069795961ff073bc090c8380eee852/isso/ext/notifications.py#L177) of notifications.py:
```
        if subject == None:
            subject = ""
```

I suppose it'd be a bit neater to do something like in `notify_users` with
```
subject = "Re: New comment posted on %s" % thread["title"]
```
into `notify_new`.

I would put together a pull request, but now I'm worried there's more corner cases like this, and my hack for notifications.py is not very pythonic 😋

Cheers,
~rf

**Comment by aquatix** [comment]
Setting subject to '' does not even work for me, as the comment would not really be submitted correctly (it'll be in the DB, but the form will not go through and no mail will be sent, as the subject is empty).
After doing the subject = "New comments posted on" ... trick like @RedFlames suggested, it works fine, so that might be a good change.

**Comment by aquatix** [comment]
I created a pull request based on @RedFlames suggestion and my own tests, making sure the email subject is never empty, and has a decent title.

**Comment by ix5** [comment]
Fixed by https://github.com/posativ/isso/pull/589
