### ISSUE TITLE
ImportError: cannot import name SharedDataMiddleware

### ISSUE THREAD

**Issue by angristan** [posativ/isso#611]
I did a simple `pip install isso` and now Isso won't start. I have been using it for 2 years without any issues, I can't seem to find what's wrong. I also tried with Python 3.

```
isso@isso ~> pip install isso
Collecting isso
Collecting ipaddr>=2.1; python_version == "2.7" (from isso)
Collecting itsdangerous (from isso)
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Jinja2 (from isso)
  Using cached https://files.pythonhosted.org/packages/27/24/4f35961e5c669e96f6559760042a55b9bcfcdb82b9bdb3c8753dbe042e35/Jinja2-2.11.1-py2.py3-none-any.whl
Collecting werkzeug>=0.9 (from isso)
  Using cached https://files.pythonhosted.org/packages/ba/a5/d6f8a6e71f15364d35678a4ec8a0186f980b3bd2545f40ad51dd26a87fb1/Werkzeug-1.0.0-py2.py3-none-any.whl
Collecting html5lib (from isso)
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
Collecting configparser; python_version == "2.7" (from isso)
  Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Collecting bleach (from isso)
  Using cached https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl
Collecting misaka<3.0,>=2.0 (from isso)
Collecting MarkupSafe>=0.23 (from Jinja2->isso)
  Using cached https://files.pythonhosted.org/packages/fb/40/f3adb7cf24a8012813c5edb20329eb22d5d8e2a0ecf73d21d6b85865da11/MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six>=1.9 (from html5lib->isso)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting webencodings (from html5lib->isso)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting cffi>=1.0.0 (from misaka<3.0,>=2.0->isso)
  Using cached https://files.pythonhosted.org/packages/08/29/8001b940ef40e7a25ffe8f3188bc9b118934b513d64f769dbf461e46f4ed/cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.0.0->misaka<3.0,>=2.0->isso)
Installing collected packages: ipaddr, itsdangerous, MarkupSafe, Jinja2, werkzeug, six, webencodings, html5lib, configparser, bleach, pycparser, cffi, misaka, isso
Successfully installed Jinja2-2.11.1 MarkupSafe-1.1.1 bleach-3.1.0 cffi-1.14.0 configparser-4.0.2 html5lib-1.0.1 ipaddr-2.2.0 isso-0.12.2 itsdangerous-1.1.0 misaka-2.1.1 pycparser-2.19 six-1.14.0 webencodings-0.5.1 werkzeug-1.0.0
```

```
isso@isso ~> isso
Traceback (most recent call last):
  File "/home/isso/.local/bin/isso", line 7, in <module>
    from isso import main
  File "/home/isso/.local/lib/python2.7/site-packages/isso/__init__.py", line 60, in <module>
    from werkzeug.wsgi import SharedDataMiddleware
ImportError: cannot import name SharedDataMiddleware
```

```
isso@isso ~> pip freeze
asn1crypto==0.24.0
bleach==3.1.0
cffi==1.14.0
configparser==4.0.2
cryptography==2.1.4
enum34==1.1.6
html5lib==1.0.1
idna==2.6
ipaddr==2.2.0
ipaddress==1.0.17
isso==0.12.2
itsdangerous==1.1.0
Jinja2==2.11.1
keyring==10.6.0
keyrings.alt==3.0
MarkupSafe==1.1.1
misaka==2.1.1
pycparser==2.19
pycrypto==2.6.1
pygobject==3.26.1
python-apt==1.6.4
pyxdg==0.25
SecretStorage==2.3.1
six==1.14.0
webencodings==0.5.1
Werkzeug==1.0.0
```

**Comment by angristan** [comment]
Rolled back Werkzeug which [published 1.0.0 5 days ago](https://github.com/pallets/werkzeug/releases):

```
isso@isso ~> pip install Werkzeug==0.16.1
Collecting Werkzeug==0.16.1
  Using cached https://files.pythonhosted.org/packages/c2/e4/a859d2fe516f466642fa5c6054fd9646271f9da26b0cac0d2f37fc858c8f/Werkzeug-0.16.1-py2.py3-none-any.whl
Installing collected packages: Werkzeug
Successfully installed Werkzeug-0.16.1
isso@isso ~> isso
usage: isso [-h] [--version] [-c /etc/isso.conf] {import,run} ...
isso: error: too few arguments
```
