### ISSUE TITLE
ModuleNotFoundError and smtplib.SMTPNotSupportedError

### ISSUE THREAD

**Issue by hamoid** [posativ/isso#633]
Hi! I see these errors in isso.log:

```
unable to connect to SMTP server
Traceback (most recent call last):
  File "/home/bbb/isso/lib/python3.6/site-packages/isso-0.12.3.dev0-py3.6.egg/isso/__init__.py", line 269, in main
    from gevent.pywsgi import WSGIServer
ModuleNotFoundError: No module named 'gevent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bbb/isso/lib/python3.6/site-packages/isso-0.12.3.dev0-py3.6.egg/isso/ext/notifications.py", line 85, in __init__
    with SMTPConnection(self.conf):
  File "/home/bbb/isso/lib/python3.6/site-packages/isso-0.12.3.dev0-py3.6.egg/isso/ext/notifications.py", line 65, in __enter__
    self.client.login(username, password)
  File "/usr/lib/python3.6/smtplib.py", line 697, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
connected to https://foo.org/
```

Is there something I should install? As it ends with "connected", does it mean that it's partially working? I can access the admin panel, but the js/css files give me 404.

**Comment by jelmer** [comment]
It looks like you have smtp credentials configured but your SMTP server doesn't support them.

**Comment by hamoid** [comment]
I have exactly the same credentials in Mattermost and Isso. 
Mattermost sends e-mails fine. 
Why could that be?

**Comment by hamoid** [comment]
This post
https://stackoverflow.com/questions/37224073/smtp-auth-extension-not-supported-by-server
led me to figure out that I just needed to **comment out the password line from isso.cfg**

**Comment by jelmer** [comment]
Yeah, an empty password string is still consider *a* password rather than absence of a password.
