### ISSUE TITLE
docker isn't creating database

### ISSUE THREAD

**Issue by titanz18** [posativ/isso#949]
hey,
i was wanted to create a isso docker but it didn't worked for me.
my docker config looks like this:
```
docker run --rm --name isso -p 127.0.0.1:3007:8080 \
    -v /root/conf-isso/config:/config -v /root/conf-isso/db:/db \
    isso
```
if i run these commands my output would look like this:
```
❯ ./isso.sh 
Traceback (most recent call last):
  File "/isso/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/isso/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/isso/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/isso/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/isso/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/isso/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/isso/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/isso/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/isso/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/isso/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/isso/isso/run.py", line 16, in <module>
    application = make_app(
  File "/isso/isso/__init__.py", line 185, in make_app
    isso = App(conf)
  File "/isso/isso/__init__.py", line 101, in __init__
    self.db = db.SQLite3(conf.get('general', 'dbpath'), conf)
  File "/isso/isso/db/__init__.py", line 32, in __init__
    rv = self.execute([
  File "/isso/isso/db/__init__.py", line 59, in execute
    with sqlite3.connect(self.path) as con:
sqlite3.OperationalError: unable to open database file
```
the only thing i got is the conf file, because i first thought, the problem would be the missing conf file (got different errors without it).
my isso.cfg looks like this:
```
 [general]
 host = https://comments.conorz.tk/
 dbpath = /root/conf-isso/db/comments.conorz.tk.db
 [server]
 listen = http://localhost:3006/
 [admin]
 enabled = true
 password = my_password
```

**Comment by jelmer** [comment]
your dbpath refers to the external path rather than the path inside of the container
